// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: utils/messagetypes.proto

package utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PicoDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value       string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Time        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
	RequestType int32                  `protobuf:"varint,4,opt,name=RequestType,proto3" json:"RequestType,omitempty"`
}

func (x *PicoDBRequest) Reset() {
	*x = PicoDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utils_messagetypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicoDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicoDBRequest) ProtoMessage() {}

func (x *PicoDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utils_messagetypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicoDBRequest.ProtoReflect.Descriptor instead.
func (*PicoDBRequest) Descriptor() ([]byte, []int) {
	return file_utils_messagetypes_proto_rawDescGZIP(), []int{0}
}

func (x *PicoDBRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PicoDBRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PicoDBRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *PicoDBRequest) GetRequestType() int32 {
	if x != nil {
		return x.RequestType
	}
	return 0
}

type PicoDBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *PicoDBResponse) Reset() {
	*x = PicoDBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utils_messagetypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicoDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicoDBResponse) ProtoMessage() {}

func (x *PicoDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utils_messagetypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicoDBResponse.ProtoReflect.Descriptor instead.
func (*PicoDBResponse) Descriptor() ([]byte, []int) {
	return file_utils_messagetypes_proto_rawDescGZIP(), []int{1}
}

func (x *PicoDBResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PicoDBResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PicoDBServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType     int32  `protobuf:"varint,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Key             string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value           string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	SourceIPAddress string `protobuf:"bytes,4,opt,name=sourceIPAddress,proto3" json:"sourceIPAddress,omitempty"`
}

func (x *PicoDBServerMessage) Reset() {
	*x = PicoDBServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utils_messagetypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicoDBServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicoDBServerMessage) ProtoMessage() {}

func (x *PicoDBServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_utils_messagetypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicoDBServerMessage.ProtoReflect.Descriptor instead.
func (*PicoDBServerMessage) Descriptor() ([]byte, []int) {
	return file_utils_messagetypes_proto_rawDescGZIP(), []int{2}
}

func (x *PicoDBServerMessage) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *PicoDBServerMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PicoDBServerMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PicoDBServerMessage) GetSourceIPAddress() string {
	if x != nil {
		return x.SourceIPAddress
	}
	return ""
}

var File_utils_messagetypes_proto protoreflect.FileDescriptor

var file_utils_messagetypes_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x74, 0x69, 0x6c,
	0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x0d, 0x50, 0x69, 0x63, 0x6f, 0x44, 0x42, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2e, 0x0a, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x38,
	0x0a, 0x0e, 0x50, 0x69, 0x63, 0x6f, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x89, 0x01, 0x0a, 0x13, 0x50, 0x69, 0x63,
	0x6f, 0x44, 0x42, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x53, 0x61, 0x73, 0x68, 0x77, 0x61, 0x74, 0x41, 0x6e, 0x61, 0x67, 0x6f, 0x6c,
	0x75, 0x6d, 0x2f, 0x70, 0x69, 0x63, 0x6f, 0x64, 0x62, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_utils_messagetypes_proto_rawDescOnce sync.Once
	file_utils_messagetypes_proto_rawDescData = file_utils_messagetypes_proto_rawDesc
)

func file_utils_messagetypes_proto_rawDescGZIP() []byte {
	file_utils_messagetypes_proto_rawDescOnce.Do(func() {
		file_utils_messagetypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_utils_messagetypes_proto_rawDescData)
	})
	return file_utils_messagetypes_proto_rawDescData
}

var file_utils_messagetypes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_utils_messagetypes_proto_goTypes = []interface{}{
	(*PicoDBRequest)(nil),         // 0: utils.PicoDBRequest
	(*PicoDBResponse)(nil),        // 1: utils.PicoDBResponse
	(*PicoDBServerMessage)(nil),   // 2: utils.PicoDBServerMessage
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_utils_messagetypes_proto_depIdxs = []int32{
	3, // 0: utils.PicoDBRequest.Time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_utils_messagetypes_proto_init() }
func file_utils_messagetypes_proto_init() {
	if File_utils_messagetypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_utils_messagetypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicoDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_utils_messagetypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicoDBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_utils_messagetypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicoDBServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_utils_messagetypes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utils_messagetypes_proto_goTypes,
		DependencyIndexes: file_utils_messagetypes_proto_depIdxs,
		MessageInfos:      file_utils_messagetypes_proto_msgTypes,
	}.Build()
	File_utils_messagetypes_proto = out.File
	file_utils_messagetypes_proto_rawDesc = nil
	file_utils_messagetypes_proto_goTypes = nil
	file_utils_messagetypes_proto_depIdxs = nil
}
