// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: utils/observerservice.proto

package utils

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PicoDBObserverClient is the client API for PicoDBObserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PicoDBObserverClient interface {
	Notify(ctx context.Context, in *PicoDBServerMessage, opts ...grpc.CallOption) (*PicoDBServerMessage, error)
}

type picoDBObserverClient struct {
	cc grpc.ClientConnInterface
}

func NewPicoDBObserverClient(cc grpc.ClientConnInterface) PicoDBObserverClient {
	return &picoDBObserverClient{cc}
}

func (c *picoDBObserverClient) Notify(ctx context.Context, in *PicoDBServerMessage, opts ...grpc.CallOption) (*PicoDBServerMessage, error) {
	out := new(PicoDBServerMessage)
	err := c.cc.Invoke(ctx, "/utils.PicoDBObserver/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PicoDBObserverServer is the server API for PicoDBObserver service.
// All implementations must embed UnimplementedPicoDBObserverServer
// for forward compatibility
type PicoDBObserverServer interface {
	Notify(context.Context, *PicoDBServerMessage) (*PicoDBServerMessage, error)
	mustEmbedUnimplementedPicoDBObserverServer()
}

// UnimplementedPicoDBObserverServer must be embedded to have forward compatible implementations.
type UnimplementedPicoDBObserverServer struct {
}

func (UnimplementedPicoDBObserverServer) Notify(context.Context, *PicoDBServerMessage) (*PicoDBServerMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedPicoDBObserverServer) mustEmbedUnimplementedPicoDBObserverServer() {}

// UnsafePicoDBObserverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PicoDBObserverServer will
// result in compilation errors.
type UnsafePicoDBObserverServer interface {
	mustEmbedUnimplementedPicoDBObserverServer()
}

func RegisterPicoDBObserverServer(s grpc.ServiceRegistrar, srv PicoDBObserverServer) {
	s.RegisterService(&PicoDBObserver_ServiceDesc, srv)
}

func _PicoDBObserver_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PicoDBServerMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PicoDBObserverServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/utils.PicoDBObserver/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PicoDBObserverServer).Notify(ctx, req.(*PicoDBServerMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PicoDBObserver_ServiceDesc is the grpc.ServiceDesc for PicoDBObserver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PicoDBObserver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "utils.PicoDBObserver",
	HandlerType: (*PicoDBObserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _PicoDBObserver_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "utils/observerservice.proto",
}
