// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: utils/serverservice.proto

package utils

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PicoDBServerClient is the client API for PicoDBServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PicoDBServerClient interface {
	ProcessRequest(ctx context.Context, in *PicoDBRequest, opts ...grpc.CallOption) (*PicoDBResponse, error)
}

type picoDBServerClient struct {
	cc grpc.ClientConnInterface
}

func NewPicoDBServerClient(cc grpc.ClientConnInterface) PicoDBServerClient {
	return &picoDBServerClient{cc}
}

func (c *picoDBServerClient) ProcessRequest(ctx context.Context, in *PicoDBRequest, opts ...grpc.CallOption) (*PicoDBResponse, error) {
	out := new(PicoDBResponse)
	err := c.cc.Invoke(ctx, "/utils.PicoDBServer/ProcessRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PicoDBServerServer is the server API for PicoDBServer service.
// All implementations must embed UnimplementedPicoDBServerServer
// for forward compatibility
type PicoDBServerServer interface {
	ProcessRequest(context.Context, *PicoDBRequest) (*PicoDBResponse, error)
	mustEmbedUnimplementedPicoDBServerServer()
}

// UnimplementedPicoDBServerServer must be embedded to have forward compatible implementations.
type UnimplementedPicoDBServerServer struct {
}

func (UnimplementedPicoDBServerServer) ProcessRequest(context.Context, *PicoDBRequest) (*PicoDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessRequest not implemented")
}
func (UnimplementedPicoDBServerServer) mustEmbedUnimplementedPicoDBServerServer() {}

// UnsafePicoDBServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PicoDBServerServer will
// result in compilation errors.
type UnsafePicoDBServerServer interface {
	mustEmbedUnimplementedPicoDBServerServer()
}

func RegisterPicoDBServerServer(s grpc.ServiceRegistrar, srv PicoDBServerServer) {
	s.RegisterService(&PicoDBServer_ServiceDesc, srv)
}

func _PicoDBServer_ProcessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PicoDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PicoDBServerServer).ProcessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/utils.PicoDBServer/ProcessRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PicoDBServerServer).ProcessRequest(ctx, req.(*PicoDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PicoDBServer_ServiceDesc is the grpc.ServiceDesc for PicoDBServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PicoDBServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "utils.PicoDBServer",
	HandlerType: (*PicoDBServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessRequest",
			Handler:    _PicoDBServer_ProcessRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "utils/serverservice.proto",
}
